package com.checkmate.learning.model

import androidx.room.Entity
import androidx.room.Index
import androidx.room.PrimaryKey

/**
 * Upgrade Blueprint Phase 1.2 ("Question data model — currently missing entirely").
 *
 * A question bank row. `id` is caller-supplied (not autogenerated) because
 * questions need to be stably re-referenced across imports — e.g. the same PYQ
 * appearing in two different Testmate mock tests must map to the same row, not
 * a duplicate. [com.checkmate.learning.testmate.TestResultNormalizer] derives a
 * deterministic id from (exam, source test title, question number) when Testmate
 * doesn't supply a canonical question id — see that file for the exact scheme.
 *
 * `subject`/`chapter`/`topic`/`concepts` are left nullable/empty rather than
 * guessed from chapter-name text (e.g. inferring "Chemistry" from "Some Basic
 * Concepts of Chemistry"). That classification belongs to the versioned NTA
 * syllabus tree the blueprint calls for in Phase 1.4 (KnowledgeGraph), not to a
 * hardcoded keyword heuristic here that would silently break for JEE/CUET chapter
 * names it wasn't written against.
 */
@Entity(
    tableName = "questions",
    indices = [
        Index(value = ["subject"]),
        Index(value = ["chapter"]),
        Index(value = ["exam"])
    ]
)
data class Question(
    @PrimaryKey val id: String,
    /** e.g. "testmate_report", "manual_entry". Never guessed — always caller-supplied. */
    val source: String,
    val year: Int? = null,
    /** e.g. "NEET-2027". Matches the exam label Testmate reports use verbatim. */
    val exam: String? = null,
    val subject: String? = null,
    val chapter: String? = null,
    val topic: String? = null,
    val concepts: List<String> = emptyList(),
    val difficulty: String? = null,
    val questionType: String? = null,
    val correctOption: String? = null,
    val questionText: String? = null,
    val explanation: String? = null,
    val officialSource: String? = null
)
